server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudstorage?createDatabaseIfNotExist=true
    username: root
    password: mysql

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true

jwt:
  token:
    secret: 7mXoDFP1JU9NAjGWGhDvyyBZPiP243ND5E8ZezudZja2Rle2O9cL
    lifetime-in-minutes: 60
    check-interval: PT120M

cors:
  path-pattern: /**
  credentials: true
  origins: http://localhost:8080
  methods: '*'